
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-10T13:45:30-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f715de41af520a726f980d2d05b49080b6230e17",
 "version": "0.6.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
